[package]
authors = ["Casey Primozic <me@ameo.link>"]
name = "libcomposition"
version = "0.1.0"

[dependencies]
itertools = "0.7.8"
lazy_static = "1.0.2"
noise = "0.5.1"
palette = "0.4.0"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
